### ISSUE TITLE
Is `defer` always the right option?

### ISSUE THREAD

**Issue by necolas** [mklabs/h5bp-build-script-tags#1]
In the example output in the README, the header script include the `defer` attribute. But, assuming the developer knows what they are doing, if you are putting scripts in the head they are likely to be libs like Modernizr or Respond...which you don't want deferred.

So maybe this attribute shouldn't be included by default?

**Comment by mklabs** [comment]
Definitely!

Right now, the current implementation relies on some kind of "processors" (js/css) and there's no configuration hook on how processors should replace the html markup. This is kinda hardcoded and coupled to each processor.

We can probably think of some sort of semantic on these `<!-- -[[ build processor path/to/bundle.extension ]] ->`. I don't know how yet, but I'm thinking that some configuration hooks should be available to use from within the html markup.

This way, developpers could tell whether they want to add to the scripts tag a `defer` attribute or not.

**Comment by mklabs** [comment]
Also, I'll probably explore the use of data-attributes as mentioned in the original issue thread.

Probably, processors could gain access to any kind of configurations by using them:

``` html
<script data-build="js/app.js" data-build-anything="conf" src="script.js">
```

May become really verbose though.

**Comment by necolas** [comment]
Yeah the `data-*` approach might get pretty tedious if you're including lots of scripts and stylesheets. 

I'm not sure what the balance should be between what can be configured in the HTML and what should remain in a separate config file. But if you wanted to include more config options directly in the HTML, maybe we can use existing conventions or object notation.

```
<!-- [[build config = {
    "output" : "app.js",
    "filter" : "yuicompressor",
    "defer" : true
}]] -->

<!-- [[endbuild]] -->
```

Probably worth getting @roblarsen @KushalP and the other guys involved in thinking up some sensible options too.
